#
# Copyright (C) 2021 Crowds Technologies LLC. All rights reserved.
#
# Distributed under MIT License
# See: https://github.com/CrowdsTech/cocos2d-x-CI/blob/main/LICENSE
#

name: CI

on:
  push:
    paths:
    - '.github/workflows/ci.yml'

jobs:
  build:
    strategy:
      matrix:
        include:
          # - os: macos-latest
          #   host: mac
          #   flavor: Release
          #   variation: mac
          # - os: macos-latest
          #   host: mac
          #   flavor: Release
          #   variation: ios
          # - os: ubuntu-latest
          #   host: linux
          #   flavor: Release
          #   variation: linux
          - os: ubuntu-latest
            host: linux
            flavor: Release
            variation: android
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - name: System Overview
      timeout-minutes: 1
      run: |
        set -x
        uname -a
        df -h
        ulimit -a
        if [ "${{ matrix.host }}" == "linux" ]; then
            sudo swapon --show
            free -h
        fi
    - name: Checkout Sources
      timeout-minutes: 1
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.7' # cocos2d-x scripts refuse to work with python3
    - name: Setup Environment Variables
      timeout-minutes: 1
      run: |
        export COCOS_X_ROOT=${GITHUB_WORKSPACE}/external/cocos2d-x
        export COCOS_CONSOLE_ROOT=${COCOS_X_ROOT}/tools/cocos2d-console/bin
        export COCOS_TEMPLATES_ROOT=${COCOS_X_ROOT}/templates
        export JAVA_HOME=${JAVA_HOME_11_X64}
        # Persist exported variables between steps in GitHub Actions
        echo "COCOS_X_ROOT=$COCOS_X_ROOT" >> $GITHUB_ENV
        echo "COCOS_CONSOLE_ROOT=$COCOS_CONSOLE_ROOT" >> $GITHUB_ENV
        echo "COCOS_TEMPLATES_ROOT=$COCOS_TEMPLATES_ROOT" >> $GITHUB_ENV
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "${COCOS_X_ROOT}" >> $GITHUB_PATH
        echo "${COCOS_CONSOLE_ROOT}" >> $GITHUB_PATH
        echo "${COCOS_TEMPLATES_ROOT}" >> $GITHUB_PATH
        set
    - name: Download Shared Dependencies
      timeout-minutes: 4
      run: |
        # If building tip of the v4 branch fails, try the latest tag 'cocos2d-x-4.0' this workflow handles instead
        git clone https://github.com/cocos2d/cocos2d-x.git -b v4 --depth=1 --single-branch
        pushd cocos2d-x
        python download-deps.py --remove-download=yes
        git submodule update --init
        popd
      working-directory: ./external
    - name: Install Dependencies (Linux)
      if: matrix.variation == 'linux'
      working-directory: ./external
      timeout-minutes: 10
      run: |
        # Note: official way fails, so we just copy their cocos2d-x dependencies without lua dependencies below
        # pushd ${GITHUB_WORKSPACE}/external/cocos2d-x
        # yes | ./install-deps-linux.sh
        # popd
        sudo apt-get update
        sudo apt-get install --yes libxxf86vm-dev libx11-dev libxmu-dev libglu1-mesa-dev libgl2ps-dev libxi-dev libzip-dev libpng-dev libcurl4-gnutls-dev libfontconfig1-dev libsqlite3-dev libglew-dev libssl-dev libgtk-3-dev binutils
    - name: Create Hello World
      timeout-minutes: 2
      run: |
        cocos new -p com.crowdstech.cocos2d_ci -e ${GITHUB_WORKSPACE}/external/cocos2d-x --portrait -l cpp --agreement n --ios-bundleid com.crowdstech.cocos2d-ci --mac-bundleid com.crowdstech.cocos2d-ci MyCocos4Proj
    - name: Build (Linux)
      if: matrix.variation == 'linux'
      working-directory: ./MyCocos4Proj
      timeout-minutes: 20
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            # Workaround for linker error that appeared the moment GitHub runners for
            # linux moved from Ubuntu 18.04.5 to Ubuntu 20.04.2 for ubuntu-latest
            # See: https://github.com/cocos2d/cocos2d-x/issues/20471
            wget https://github.com/cocos2d/cocos2d-x/files/4272227/libchipmunk7.0.1.zip
            unzip libchipmunk7.0.1.zip
            mv libchipmunk.* cocos2d/external/chipmunk/prebuilt/linux/64-bit/
        fi
        mkdir build-${{ matrix.variation }}
        pushd build-${{ matrix.variation }}
        cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.flavor }}
        make
        ls -alFR
        popd
    - name: Build (Android)
      if: matrix.variation == 'android'
      working-directory: ./MyCocos4Proj
      timeout-minutes: 20
      run: |
        sed -i -e "s/gradle-5.1.1-all.zip/gradle-6.7.1-all.zip/g" proj.android/gradle/wrapper/gradle-wrapper.properties
        sed -i -e "s/com.android.tools.build:gradle:3.1.0/com.android.tools.build:gradle:3.4.2/g" proj.android/build.gradle
        sed -i -e "s/cppFlags/version \"3.10.2\"\n                cppFlags/g" proj.android/app/build.gradle
        cat proj.android/app/build.gradle
        # Note: the above version doesn't work for some reason, so just manually change cmake 3.6 to 3.10 requirement in all cocos
        find . -name CMakeLists.txt | xargs sed -i -e "s/cmake_minimum_required(VERSION 3.6)/cmake_minimum_required(VERSION 3.10)/g"
        pushd proj.android
        ./gradlew assembleRelease -PPROP_BUILD_TYPE=cmake --parallel --info --debug
        ls -alFR
        popd
    - name: Build (macOS)
      if: matrix.variation == 'mac'
      working-directory: ./MyCocos4Proj
      timeout-minutes: 20
      run: |
        mkdir build-${{ matrix.variation }}
        pushd build-${{ matrix.variation }}
        cmake .. -GXcode -DCMAKE_XCODE_ATTRIBUTE_MACOSX_DEPLOYMENT_TARGET=10.12
        cmake --build . --config ${{ matrix.flavor }}
        ls -alFR
        popd
    - name: Install the Apple certificate and provisioning profile (iOS)
      if: matrix.variation == 'ios'
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # Source: https://docs.github.com/en/actions/deployment/installing-an-apple-certificate-on-macos-runners-for-xcode-development

        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
    - name: Build (iOS)
      if: matrix.variation == 'ios'
      working-directory: ./MyCocos4Proj
      timeout-minutes: 30
      run: |
        sed -i -e "s/org.cocos2dx.\${PRODUCT_NAME}/com.crowdstech.cocos2d-ci/g" proj.ios_mac/ios/Info.plist
        sed -i -e "s/\"\/usr\/lib\/libz.dylib\"/\${Z_LIBRARY}/g"         cocos2d/cmake/Modules/CocosConfigDepend.cmake
        sed -i -e "s/\"\/usr\/lib\/libiconv.dylib\"/\${ICONV_LIBRARY}/g" cocos2d/cmake/Modules/CocosConfigDepend.cmake
        # We use bash \n substitution below because of OS X problem described in https://superuser.com/questions/307165/newlines-in-sed-on-mac-os-x
        sed -i -e $'s/Locate system libraries on iOS/Locate system libraries on iOS\\\nfind_library(ICONV_LIBRARY iconv)\\\nfind_library(Z_LIBRARY z)/g' cocos2d/cmake/Modules/CocosConfigDepend.cmake
        mkdir build-${{ matrix.variation }}
        pushd build-${{ matrix.variation }}
        cmake .. -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphoneos  -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY="iPhone Developer" -DCMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM=${{ secrets.DEVELOPMENT_TEAM }} -DCMAKE_XCODE_ATTRIBUTE_PROVISIONING_PROFILE_SPECIFIER=Cocos2dCIDevPro -DCMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET=9.0
        cmake --build . --config ${{ matrix.flavor }} -- -allowProvisioningUpdates
        ls -alFR
        popd
    - name: Clean up keychain and provisioning profile (iOS)
      if: matrix.variation == 'ios' && always()
      run: |
        security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
        rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
